"""empty message

Revision ID: e0f71bc0a169
Revises: dd63b52b7116
Create Date: 2023-10-31 12:00:04.053744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f71bc0a169'
down_revision = 'dd63b52b7116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usertickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.drop_column('title')
        batch_op.drop_column('submitted_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usertickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_by', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
